import type { Metadata } from "next"
import { Bebas_Neue, DM_Sans } from "next/font/google"
import "./globals.css"

/*
 * PopupManagerLoader is a "use client" component that internally uses
 * dynamic(() => import("@/components/ui/PopupManager"), { ssr: false }).
 *
 * We cannot call dynamic(..., { ssr: false }) at the module level of a
 * Server Component (layout.tsx is a Server Component by default in App Router).
 * Moving the dynamic() call into a dedicated Client Component is the correct
 * Next.js App Router pattern — keeps layout a Server Component, keeps the
 * popup client-only, zero Lighthouse impact.
 */
import { PopupManagerLoader } from "@/components/ui/PopupManagerLoader"

import { AuthProvider }            from "@/contexts/AuthContext"
import { MotionProvider }          from "@/components/providers/MotionProvider"
import { SmoothScrollProvider }   from "@/components/providers/SmoothScrollProvider"
import { PageTransitionProvider } from "@/components/providers/PageTransitionProvider"
import { SiteHeader }             from "@/components/layout/SiteHeader"
import { SiteFooter }             from "@/components/layout/SiteFooter"
import { CartDrawer }             from "@/components/cart/CartDrawer"
import { NavProgressBar }         from "@/components/ui/NavProgressBar"
import { OnboardingModal }        from "@/components/onboarding/OnboardingModal"
import { OnboardingGate }         from "@/components/onboarding/OnboardingGate"
import { GlobalAmbientWrapper }   from "@/components/3d/GlobalAmbientWrapper"
import { siteConfig }             from "@/config/site"
import { organizationSchema, websiteSchema } from "@/lib/seo/schemas"

/* ── Display font — headings, hero text, section titles ── */
const bebasNeue = Bebas_Neue({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bebas",
  display: "swap",
})

/* ── Body font — paragraphs, buttons, nav, labels ──
   Weights loaded match every weight class used in the UI so the browser
   never has to synthesise a faux weight:
     300 light · 400 regular · 500 medium · 600 semibold · 700 bold
   (font-bold / font-bold are normalised to font-bold app-wide — a
   700 cap reads more editorial/premium than a synthetic 900.) */
const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-dm-sans",
  display: "swap",
})

/* ── Root metadata ─────────────────────────────────────────
   metadataBase is CRITICAL — without it Next.js cannot resolve
   relative OG image paths to absolute URLs required by social
   scrapers (Twitter, Facebook, Discord, Slack).
──────────────────────────────────────────────────────────── */
export const metadata: Metadata = {
  metadataBase: new URL(siteConfig.url),

  title: {
    default:  "PXL Creator — Premium Cinematic Presets",
    template: "%s | PXL Creator",
  },
  description:
    "Handcrafted Lightroom presets, cinematic editing tools, and creator resources for photographers and filmmakers.",
  keywords: [
    "lightroom presets",
    "cinematic presets",
    "photo editing presets",
    "lightroom mobile presets",
    "cinematic lightroom presets",
    "film emulation presets",
    "portrait presets",
    "landscape presets",
    "street photography presets",
    "creator tools",
    "photography presets",
    "PXL Creator",
  ],
  authors:  [{ name: "PXL Creator", url: siteConfig.url }],
  creator:  "PXL Creator",
  publisher: "PXL Creator",

  /* ── Canonical + alternates ── */
  alternates: {
    canonical: siteConfig.url,
  },

  /* ── Robots ── */
  robots: {
    index:        true,
    follow:       true,
    googleBot: {
      index:            true,
      follow:           true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet":       -1,
    },
  },

  /* ── OpenGraph ── */
  openGraph: {
    type:        "website",
    locale:      "en_US",
    url:          siteConfig.url,
    siteName:     siteConfig.name,
    title:       "PXL Creator — Premium Cinematic Presets",
    description: "Handcrafted Lightroom presets, cinematic editing tools, and creator resources for photographers and filmmakers.",
    // OG image is auto-generated by src/app/opengraph-image.tsx
  },

  /* ── Twitter / X ── */
  twitter: {
    card:        "summary_large_image",
    title:       "PXL Creator — Premium Cinematic Presets",
    description: "Handcrafted Lightroom presets, cinematic editing tools, and creator resources.",
    // Twitter image is auto-generated from opengraph-image.tsx
  },

  /* ── Verification (add keys when available) ── */
  // verification: {
  //   google: "YOUR_GOOGLE_SITE_VERIFICATION",
  // },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${bebasNeue.variable} ${dmSans.variable}`}>
      {/*
        flex + min-h-screen on body ensures:
        - SiteHeader stays at top
        - <main> grows to fill available space
        - SiteFooter stays pinned at the bottom on short pages
      */}
      <body className="flex min-h-screen flex-col bg-background text-foreground antialiased">

        {/* ── Global JSON-LD structured data ─────────────────
            Organisation + WebSite schemas live here once and
            apply to every page. Page-level schemas (Product,
            Article, Breadcrumb) are injected by each page.
        ─────────────────────────────────────────────────── */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(organizationSchema()),
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(websiteSchema()),
          }}
        />

        {/* ── Global persistent 3D ambient layer — behind all content ── */}
        <GlobalAmbientWrapper />

        {/* ── Route navigation progress bar ── */}
        <NavProgressBar />

        {/* ── Skip to content (WCAG 2.4.1 Bypass Blocks) ──
            Visually hidden until focused; lets keyboard + screen-reader
            users jump past the header/nav straight to the main content. */}
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[100] focus:rounded-lg focus:bg-gold focus:px-4 focus:py-2 focus:text-[0.875rem] focus:font-semibold focus:text-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
        >
          Skip to content
        </a>

        <SmoothScrollProvider>
          <MotionProvider>
          <AuthProvider>
            <SiteHeader />
            <PageTransitionProvider>
              <main id="main-content" className="flex-1">
                {children}
              </main>
            </PageTransitionProvider>
            <SiteFooter />
            {/* CartDrawer is mounted once at the root — available on every page */}
            <CartDrawer />
            {/* Onboarding — checks status after sign-in, shows modal if needed */}
            <OnboardingGate />
            <OnboardingModal />
            {/* Promotional popup — client-only via PopupManagerLoader wrapper */}
            <PopupManagerLoader />
          </AuthProvider>
          </MotionProvider>
        </SmoothScrollProvider>
      </body>
    </html>
  )
}
